### ISSUE TITLE
Issue with docker-compose ps

### ISSUE THREAD

**Issue by huiwang1** [PolymeshAssociation/polymesh-local#50]
Hey project team,

I had issues trying to use `polymesh-local` due to the `docker-compose ps` call in the `containersUp` method.  

I'm currently using docker-compose V2:

```
❯ docker-compose --version
Docker Compose version v2.12.2
```

Since the `docker-compose` is being called in the same directory as the `docker-compose.yml` but without any of the environment variables defined, the `ps` call is failing with:

> WARN[0000] The "FAKETIME" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "CHAIN" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "DATA_DIR" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "DATA_DIR" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "DATA_DIR" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "DATA_DIR" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "PG_HOST" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "PG_USER" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "PG_PASSWORD" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "TOOLING_IMAGE" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "REST_IMAGE" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "VAULT_TOKEN" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "LOCAL_SIGNERS" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "LOCAL_MNEMONICS" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "VAULT_URL" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "TOOLING_API_KEY" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "DATA_DIR" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "DATA_DIR" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "PG_DB" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "PG_PORT" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "PG_HOST" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "PG_USER" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "PG_PASSWORD" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "SUBQUERY_IMAGE" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "DATA_DIR" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "DATA_DIR" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "DATA_DIR" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "POLYMESH_VERSION" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "DATA_DIR" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "FAKETIME" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "CHAIN" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "FAKETIME" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "CHAIN" variable is not set. Defaulting to a blank string. 
> service "subquery" has neither an image nor a build context specified: invalid compose project

I could hack around this issue by creating some sensible defaults in the`docker-compose.yml`:

```
   subquery:
-    image: '${SUBQUERY_IMAGE}'
+    image: '${SUBQUERY_IMAGE:-polymeshassociation/polymesh-subquery}'
     restart: always
     depends_on:
       - 'postgres'
@@ -88,7 +88,7 @@ services:
       - --local
 
   tooling:
-    image: ${TOOLING_IMAGE}
+    image: ${TOOLING_IMAGE:-polymeshassociation/polymesh-tooling-gql}
     restart: always
     depends_on:
       - 'postgres'
@@ -101,7 +101,7 @@ services:
       STAGE: dev
 
   rest_api:
-    image: ${REST_IMAGE}
+    image: ${REST_IMAGE:-polymeshassociation/polymesh-rest-api}
     restart: always
     ports:
       - 3004:3000
```

Cheers,
Hui

**Comment by polymath-eric** [comment]
@huiwang1  Thanks for opening this, and sorry for the late response, I missed seeing this.

Is this still an issue? Setting sensible defaults for these makes sense to me, however it would be better if it would work consistently with different versions.

I am currently using `docker-compose version 1.29.2`. It seems like there is something missing for proper v2 support.

I've been meaning to migrate to the built in `docker compose` instead of needing `docker-compose` installed as well. 

If this is still an issue I can look into getting that prioritized.

**Comment by huiwang1** [comment]
Yeah I'm using docker compose v2.13.0 but by adding the sensible defaults I'm able to work around the issue. Just wanted to let you guys know for future reference. Cheers.

**Comment by polymath-eric** [comment]
For a docker compose v2 compatible version, I've been using a plain docker-compose file:

https://github.com/polymath-eric/scripts/tree/main/compose

I'll likely tweak this for my own development needs, but it should be a good place to copy and get similar functionality to polymesh-local as an alternative.
